[GEOMETRY]

; Length in meters of the whole domain [m]
LENGTH = 0.08615458

; Location of the interface [m]
INTERFACE_LOCATION = 0.05

; Simulation type topology (default, nozzle). Default is the standard shock tube, nozzle requires a nozzle csv file where info about the area is stored
TOPOLOGY = nozzle

; Location of the nozzle csv file with the distribution of areas along x. Same coordinate system and reference of the tube
NOZZLE_FILEPATH = inputs/nozzle_geometries/nozzle_orchid.csv



[SIMULATION]

; Number of points in the whole domain (equidistant points)
NUMBER_POINTS = 200

; Final time of the simulation [s]
TIME_MAX = 0.0500

; Initial densities in the left and right state
TEMPERATURE_LEFT = 288.15
TEMPERATURE_RIGHT = 288.15

; Initial velocities in the left and right state
VELOCITY_LEFT = 100
VELOCITY_RIGHT = 100

; Initial pressure in the left and right state
PRESSURE_LEFT = 80000
PRESSURE_RIGHT = 80000

; Advection scheme (roe, roe_arabi, roe_vinokur). First option does not work for real fluids.
NUMERICAL_SCHEME = roe_arabi

; Boundary conditions
BOUNDARY_CONDITION_LEFT = inlet
BOUNDARY_CONDITION_RIGHT = outlet

; Inlet ((pt, Tt, direction) or (p, h)) and Outlet (p) boundary conditions values. 
; Inlet conditions type: total or static
; static conditions for now only work in combination with the real gas model. 
INLET_CONDITIONS = 6833552.881809819, 264812.07061240845
INLET_CONDITIONS_TYPE = static
OUTLET_CONDITIONS = 136671

; Max CFL to be used <1)
CFL_MAX = 0.7

; Time step method (constant-> the cfl based time step is computed with the initial states, adaptive-> the cfl based time step is computed at every iteration)
;TIME_STEP_METHOD = adaptive


[FLUID]

; Name of the fluid, according to Coolprop
FLUID_NAME = R1234ze(E)

; Model of the fluid to be used (ideal, real)
FLUID_MODEL = real
FLUID_LIBRARY = REFPROP

; ; Gamma of the fluid (cp/cv), important if ideal gas is selected
; FLUID_GAMMA = 1.4

; ; Gas R constant [J/kgK]
; GAS_R_CONSTANT = 287.05


[OUTPUT]

; Name of output file directory, to this name, the number of points in the domain will be added automatically
RESULTS_DIRECTORY_NAME = output_recovery_copy

; Specify yes or no to show animation of results
SHOW_ANIMATION = no

; Specify amount of iterations between two consecutive writes of results to file. If set to 0, results will only be written at the end of the simulation.
WRITE_INTERVAL = 1
 
; Print info about residuals at every iteration? 
PRINT_INFO_RESIDUALS = yes

; Overwrite existing results; option will be ignored if simulation is restarted. No output will be overwritten in that case, only appended. 
OVERWRITE_RESULTS = yes