# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches:
      - CM_14_6

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: checkout to directory CM_14_6
      uses: actions/checkout@v7
      with:
        ref: CM_14_6

    - name: Install uv
      uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      with:
        # Install a specific version of uv.
        version: "0.11.14"
    
    - name: create virtual environment w/ uv based on lock file
      run: |
        uv venv
        .venv/Scripts/activate

    - name: Install dependencies in venv
      run: |
        uv pip install -e .

      
    - name: test
      run: |
        uv pip list
        
    - name: Perform regression tests
      run: |
        cd test/regression_tests/
        uv run pytest test_cases.py
        cd ../..

    - name: Perform fluid integration test
      run: |
        cd test/integration_tests/
        uv run pytest test_fluid.py
        cd ../..